* How many numbers are smaller than the curren numbers

Given the array /nums/, for each /nums[i]/ find out how many numbers in the array are smaller than it. That is, for each /nums[i]/ you have to count the number of valid /j's/  such that j != i *and* /nums[j] < nums[i]/.

Return the answer in an array.

*** Example 1:
*Input*: nums = [8,1,2,2,3]
*Output*: [4,0,1,1,3]
*Explanation*:
For nums[0]=8 there exist four smaller numbers than it (1, 2, 2 and 3).
For nums[1]=1 does not exist any smaller number than it.
For nums[2]=2 there exist one smaller number than it (1).
For nums[3]=2 there exist one smaller number than it (1).
For nums[4]=3 there exist three smaller numbers than it (1, 2 and 2).

*** Example 2:
*Input*: nums = [6,5,4,8]
*Output*: [2,1,0,3]

*** Exmaple 3:
*Input*: nums = [7,7,7,7]
*Output*: [0,0,0,0]


** Aproaches

*** Use a hash map and a sorted version of the array
Create a sorted copy of the nums array, iterate over the sorted array and if the value does not exist in the hash map add it as the key and the index of the current item as value, then iterate over the original array, get the value from the hash map using the current item and add it to the array to be returned.
